@api = https://cubecheck.onrender.com/

GET {{api}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6MjUsInJvbCI6InVzZXIiLCJ0ZWxlZm9ubyI6ODIxODE0NTMsImVtYWlsIjoiZ29tZXg2Nzk4QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEyJENiRmh5UGNOY2NHaWd3R3JjTWJHWC54LnRIVDNlckVEcXZPMThZRVI5czhpNE91c0xEWm1hIiwiZXhwIjoxNjk1NDEwODExfQ.xjGdkJelwR2bQ5P0Ia93uOK2iobUdhE5n5Z08PxBAx8

###
GET {{api}}/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6MjUsInJvbCI6ImFkbWluIiwidGVsZWZvbm8iOjgyMTgxNDUzLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NDgxNzUyOH0.iaVHE1eEKTh7JUYnU_PDdKUQL5h-vdafXfYCXHoQpWw

####
POST {{api}}/users
Content-Type: application/json

{
    "nombre": "prueba1",
    "apellido": "narvaez",
    "edad":30,
    "rol": "admin",
    "telefono":82181453,
    "email": "maximo@gmail.com",
    "password": "1dgfhhg4asd5"
}
