@api = http://127.0.0.1:5000

GET {{api}}

###obtener los usuarios
GET {{api}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5OTk4MTk3M30.bVng7OFFPasTGDhgdjHmq5BeUr_PIXD71D56LF0YZJE

###obtener los numero de usuarios x roles
GET {{api}}/nusers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5OTUwMDk3MH0.lCykygID1M7vzFRSQn8zwitGjyOO0XxrEl5_3ZW_lp8

###obtener usuario por id
GET {{api}}/user/650fc89d295fd7e51355cad0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJKdWFuIiwiYXBlbGxpZG8iOiJKaW1lbmV6IiwiZWRhZCI6MzIsInJvbCI6InVzZXIiLCJ0ZWxlZm9ubyI6NzgzNDg5MjMsImVtYWlsIjoianVhbmptMTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTIkRFRwNDRUVlJzZVI2TzNFZnpLejZXdUN6SUpXc1FsNzc4UjhtdWlhOFMvSFZGaDNHd3c5aGEiLCJleHAiOjE2OTU2ODQ0MTN9.Nn2zctLiYCUXD9qzU11TKezhy_GbvkF5svEDSUTlX8g

###ver token
GET {{api}}/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5Nzk5MDkyN30.pWf_LlrS-yaeCsIOS0mELRjeEbXSnUdyJtC4YQVZPYI


###registro de usuario
POST {{api}}/signin
Content-Type: application/json

{
    "nombre": "Max",
    "apellido": "Jimenez",
    "edad":32,
    "telefono":78348923,
    "email": "jawferw@gmail.com",
    "password": "JuanJm1"
}

###logeo de usuarios
POST {{api}}/login
Content-Type: application/json

{
    "email": "gomex6798@gmail.com",
    "password": "FREDDYGOMEZ@500"
}


###ingresar usuarios
POST {{api}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6MjUsInJvbCI6ImFkbWluIiwidGVsZWZvbm8iOjgyMTgxNDUzLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NDgxNzUyOH0.iaVHE1eEKTh7JUYnU_PDdKUQL5h-vdafXfYCXHoQpWw
Content-Type: application/json

{
    "nombre": "Freddy",
    "apellido": "Gomez",
    "edad":25,
    "rol": "admin",
    "telefono":82181453,
    "email": "max@gmail.com",
    "password": "FREDDYGOMEZ@500"
}

###eliminar usuarios
DELETE  {{api}}/user/65054369eb32259acceff080
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6MjUsInJvbCI6ImFkbWluIiwidGVsZWZvbm8iOjgyMTgxNDUzLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NDgxNzUyOH0.iaVHE1eEKTh7JUYnU_PDdKUQL5h-vdafXfYCXHoQpWw

###actulizar usuario x id
PUT {{api}}/user/65028ef9b2c1c36236870402
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6MjUsInJvbCI6ImFkbWluIiwidGVsZWZvbm8iOjgyMTgxNDUzLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NDgxNzUyOH0.iaVHE1eEKTh7JUYnU_PDdKUQL5h-vdafXfYCXHoQpWw
Content-Type: application/json

{
    "nombre": "max",
    "apellido": "steel",
    "edad":30,
    "rol": "user",
    "telefono":82181453,
    "email": "maxq@gmail.com",
    "password": "max234"
}


###buscar usuario x gmail
GET {{api}}/email/jawferw@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6MjUsInJvbCI6ImFkbWluIiwidGVsZWZvbm8iOjgyMTgxNDUzLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NDgxNzUyOH0.iaVHE1eEKTh7JUYnU_PDdKUQL5h-vdafXfYCXHoQpWw

###actualizar rol del usuario
PUT  {{api}}/rol/651cf9e093bdea2b330a82fe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5OTk4MTk3M30.bVng7OFFPasTGDhgdjHmq5BeUr_PIXD71D56LF0YZJE
Content-Type: application/json

{
    "rol": "premium"
}

###actualizar algunos datos del usuario
PUT  {{api}}/userb/65028ef9b2c1c36236870402
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6MjUsInJvbCI6ImFkbWluIiwidGVsZWZvbm8iOjgyMTgxNDUzLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NDgxNzUyOH0.iaVHE1eEKTh7JUYnU_PDdKUQL5h-vdafXfYCXHoQpWw
Content-Type: application/json

{
    "nombre": "Max",
    "apellido": "Steel",
    "edad":27,
    "telefono":82181453
}
###actalizar password del usuario
PUT  {{api}}/userp/65028ef9b2c1c36236870402
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6MjUsInJvbCI6ImFkbWluIiwidGVsZWZvbm8iOjgyMTgxNDUzLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NDgxNzUyOH0.iaVHE1eEKTh7JUYnU_PDdKUQL5h-vdafXfYCXHoQpWw
Content-Type: application/json

{
    "password":"max6798@56",
    "newPassword":"max6798@56"
}

###ingresar materiales x
POST {{api}}/materialx
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

{
    "nombre": "Hierro liso 1/4",
    "marca": "Liso",
    "tipo": "Hierro",
    "medida":"mt",
    "cantidad": 6,
    "precio": 79.84,
    "description" : "El cemento es un material fundamental en la construcción y es ampliamente utilizado en una variedad de aplicaciones. Existen varios tipos de cemento, pero el más comúnmente empleado en la construcción es el cemento Portland, que es un componente clave en la fabricación de hormigón y mortero. Aquí tienes información sobre el cemento en la construcción"
}

###obtener los materiales x
GET {{api}}/materialx
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

###eliminar material
DELETE  {{api}}/materialx/65309d2cfd08deb3025c966d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

###actualizar materiales x
PUT {{api}}/materialx/65309d2cfd08deb3025c966d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

{
    "nombre": "Holcin",
    "marca": "Holcin",
    "tipo": "Cemento",
    "medida":"Kg",
    "cantidad": 1,
    "precio": 7.29,
    "description" : "El cemento es un material fundamental en la construcción y es ampliamente utilizado en una variedad de aplicaciones. Existen varios tipos de cemento, pero el más comúnmente empleado en la construcción es el cemento Portland, que es un componente clave en la fabricación de hormigón y mortero. Aquí tienes información sobre el cemento en la construcción"
}

###ingresar materiales y
POST {{api}}/materialy
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

{
    "nombre": "Bloque",
    "tipo": "Bloque",
    "x": 12,
    "y":10,
    "z": 20,
    "precio": 80,
    "description" : "Los bloques, en el contexto de la construcción, son unidades rectangulares o cuadradas de material de construcción utilizadas para crear muros, paredes, particiones y otros elementos estructurales o decorativos. Estos bloques pueden estar hechos de diferentes materiales, y cada tipo de bloque tiene sus propias características y aplicaciones específicas. A continuación, se describen algunos de los tipos más comunes de bloques utilizados en construcción"
}

###obtener los materiales y
GET {{api}}/materialy
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

###eliminar material y
DELETE  {{api}}/materialy/6530a58c70786cffc3dd628f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

###actualizar materiales y
PUT {{api}}/materialy/6532ea73434eb04f477da33f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

{
    "nombre": "Ladrillo",
    "tipo": "Ladrillo",
    "x": 40,
    "y":20,
    "z": 87,
    "precio": 40,
    "description" : "Los bloques, en el contexto de la construcción, son unidades rectangulares o cuadradas de material de construcción utilizadas para crear muros, paredes, particiones y otros elementos estructurales o decorativos. Estos bloques pueden estar hechos de diferentes materiales, y cada tipo de bloque tiene sus propias características y aplicaciones específicas. A continuación, se describen algunos de los tipos más comunes de bloques utilizados en construcción"
}

###ingresar proyectos
POST {{api}}/proyectos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5OTk4Mjg2N30.prF_GTcLgJvEHgmhqM8bgRG7-Z935VC_2JzgsHJZcQY

{
    "nombre": "My Home",
    "descripcion": "My first Home",
    "user": "651cf9e093bdea2b330a82fe",
    "construccion": {
        "pisos": [
            {
                "paredes": 10,
                "pilares": 5
            },
            {
                "paredes": 8,
                "pilares": 4
            }
        ]
    }
}

###obtener los materiales y
GET {{api}}/proyecto/651cf9e093bdea2b330a82fe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5OTEzMDY3Nn0.RaxjrMGcyqBoWzkaai8RhXAqfz22CLWY-ra8850VVgk

###obtener los materiales y
GET {{api}}/proyectos/6551695fadeae7d6579cbb0b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5OTEzMDY3Nn0.RaxjrMGcyqBoWzkaai8RhXAqfz22CLWY-ra8850VVgk

###eliminar material y
DELETE  {{api}}/proyectos/6530aebb2a75763aba730361
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

###actualizar proyecto
PUT {{api}}/proyectos/6551c44345dae8a71b42ca3d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5ODM0NzIwMH0.M6LqQ6g_Jxohh67rmOzF-Dwe_B-JJNjjedOJJZTwXGM

{
    "alturaParedes": 3,
    "alturaPilares": 3,
    "embaldosado": [6, 0.15, 6],
    "materialBase": "Ladrillo",
    "moverPared": false,
    "moverPilar": false,
    "numeroParedes": 8,
    "numeroPilares": 8,
    "pilaresEsquinas":[
        {"x": 2.75, "y": 1.6, "z": 2.75},
        {"x": -2.75, "y": 1.6, "z": 2.75},
        {"x": -2.75, "y": 1.6, "z": -2.75},
        {"x": 2.75, "y": 1.6, "z": -2.75}
        ],
    "pilaresX": [
        {"x": 2.75, "y": 1.6, "z": -0.1}
        ],
    "pilaresXN":[
        {"x": -2.75, "y": 1.6, "z": -0.1}
        ],
    "pilaresZ":[
        {"x": 0.1, "y": 1.6, "z": 2.75}
        ],
    "pilaresZN":[
        {"x": 0.1, "y": 1.6, "z": -2.75}
        ]
}

####calcular pared
POST {{api}}/calculoPared
Content-Type: application/json

{
    "base": 4,
    "altura": 4,
    "material": "Ladrillo"
}

####calcular pilar
POST {{api}}/calculoPilar
Content-Type: application/json

{
    "largo": 0.40,
    "altura": 4,
    "ancho": 0.40
}


####calcular embaldosado
POST {{api}}/calculoEmbaldosado
Content-Type: application/json

{
    "largo": 1,
    "ancho": 1,
    "grosor": 0.15
}   


####
GET {{api}}/tools
Content-Type: application/json


###
POST {{api}}/tools
Content-Type: application/json

{
   
}

###
PUT {{api}}/tools/conversion
Content-Type: application/json