@api = http://127.0.0.1:3000

GET {{api}}

###
GET {{api}}/users

###
GET {{api}}/user/64fff3e826287fc9c4631b39

###
POST {{api}}/users
Content-Type: application/json

{
    "nombre": "max",
    "apellido": "narvaez",
    "edad":30,
    "rol": "admin",
    "telefono":82181453,
    "email": "maximo@gmail.com",
    "password": "1dgfhhg4asd5"
}

###
DELETE  {{api}}/user/64fff368c495c22893ce7c97

###
PUT {{api}}/user/64fff1cca1db83076138fa3e
Content-Type: application/json

{
    "nombre": "max1",
    "apellido": "narvaez",
    "edad":30,
    "rol": "admin",
    "telefono":82181453,
    "email": "maximo@gmail.com",
    "password": "1dgfhhg4asd5"
}