@api = http://127.0.0.1:3000

GET {{api}}

###
GET {{api}}/users
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJwcnVlYmExIiwiYXBlbGxpZG8iOiJuYXJ2YWV6IiwiZWRhZCI6MzAsInJvbCI6ImFkbWluIiwidGVsZWZvbm8iOjgyMTgxNDUzLCJlbWFpbCI6Im1heGltb0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IjFkZ2ZoaGc0YXNkNSIsImV4cCI6MTY5NDcyNjc3OH0.-oCKObfcYItqDY-JooGXILzWMqdO4fzR4eF74aQVPDo

###
GET {{api}}/user/650273358f9fdc86e0c4db41


###
GET {{api}}/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6MjUsInRlbGVmb25vIjo4MjE4MTQ1MywiZW1haWwiOiJnb21lemZyZWRkeTg4NkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IkZSRUREWUdPTUVaQDUwMCIsImV4cCI6MTY5NDgxMDU4Mn0.zLJCVNnImipPD3lSk16kOcP1uD5CRG0U2KKhvbaPok8

###
POST {{api}}/signin
Content-Type: application/json

{
    "nombre": "Jorge",
    "apellido": "Narvaez",
    "edad":23,
    "telefono":82181453,
    "email": "jn174356@gmail.com",
    "password": "jorgeN@200"
}

###
DELETE  {{api}}/user/650267ff2d8e5f7efe6bb815

###
PUT {{api}}/user/65012716086a73f5a8a320d3
Content-Type: application/json

{
    "nombre": "max1244",
    "apellido": "narvaez",
    "edad":30,
    "rol": "admin",
    "telefono":82181453,
    "email": "maximo@gmail.com",
    "password": "1dgfhhg4asd5"
}