@api = http://127.0.0.1:5000

###ingresar materiales x
POST {{api}}/materialx
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTcwMjU5NzM0NH0.A_LKhkTpxfTp0aZA2qn19maEauWTYZeX2guRr4QsIJs

{
    "nombre": "Hierro liso 1/4",
    "marca": "Liso",
    "tipo": "Hierro",
    "medida":"mt",
    "cantidad": 6,
    "precio": 64,
    "description" : "El cemento es un material fundamental en la construcción y es ampliamente utilizado en una variedad de aplicaciones. Existen varios tipos de cemento, pero el más comúnmente empleado en la construcción es el cemento Portland, que es un componente clave en la fabricación de hormigón y mortero. Aquí tienes información sobre el cemento en la construcción"
}

###obtener los materiales x
GET {{api}}/mismaterialx/65028e57b2c1c36236870401
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTcwMjU5NzM0NH0.A_LKhkTpxfTp0aZA2qn19maEauWTYZeX2guRr4QsIJs

###eliminar material
DELETE  {{api}}/materialx/65309d2cfd08deb3025c966d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

###actualizar materiales x
PUT {{api}}/materialx/65309d2cfd08deb3025c966d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

{
    "nombre": "Holcin",
    "marca": "Holcin",
    "tipo": "Cemento",
    "medida":"Kg",
    "cantidad": 1,
    "precio": 7.29,
    "description" : "El cemento es un material fundamental en la construcción y es ampliamente utilizado en una variedad de aplicaciones. Existen varios tipos de cemento, pero el más comúnmente empleado en la construcción es el cemento Portland, que es un componente clave en la fabricación de hormigón y mortero. Aquí tienes información sobre el cemento en la construcción"
}

###ingresar materiales x en uso
POST {{api}}/materialxuso
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

{
    "nombre": "Hierro liso 1/4",
    "marca": "Liso",
    "tipo": "Hierro",
    "medida":"mt",
    "cantidad": 6,
    "precio": 79.84,
    "description" : "El cemento es un material fundamental en la construcción y es ampliamente utilizado en una variedad de aplicaciones. Existen varios tipos de cemento, pero el más comúnmente empleado en la construcción es el cemento Portland, que es un componente clave en la fabricación de hormigón y mortero. Aquí tienes información sobre el cemento en la construcción"
}
