@api = http://127.0.0.1:5000

###ingresar materiales y
POST {{api}}/materialy
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

{
    "nombre": "Bloque",
    "tipo": "Bloque",
    "x": 6,
    "y":8,
    "z": 16,
    "precio": 42,
    "description" : "Los bloques, en el contexto de la construcción, son unidades rectangulares o cuadradas de material de construcción utilizadas para crear muros, paredes, particiones y otros elementos estructurales o decorativos. Estos bloques pueden estar hechos de diferentes materiales, y cada tipo de bloque tiene sus propias características y aplicaciones específicas. A continuación, se describen algunos de los tipos más comunes de bloques utilizados en construcción"
}

###obtener los materiales y
GET {{api}}/materialy
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

###eliminar material y
DELETE  {{api}}/materialy/6530a58c70786cffc3dd628f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

###actualizar materiales y
PUT {{api}}/materialy/6532ea73434eb04f477da33f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

{
    "nombre": "Ladrillo",
    "tipo": "Ladrillo",
    "x": 40,
    "y":20,
    "z": 87,
    "precio": 40,
    "description" : "Los bloques, en el contexto de la construcción, son unidades rectangulares o cuadradas de material de construcción utilizadas para crear muros, paredes, particiones y otros elementos estructurales o decorativos. Estos bloques pueden estar hechos de diferentes materiales, y cada tipo de bloque tiene sus propias características y aplicaciones específicas. A continuación, se describen algunos de los tipos más comunes de bloques utilizados en construcción"
}



###ingresar materiales y
POST {{api}}/materialyuso
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJGcmVkZHkiLCJhcGVsbGlkbyI6IkdvbWV6IiwiZWRhZCI6IjI1Iiwicm9sIjoidXNlciIsInRlbGVmb25vIjoiODIxODE2NjMiLCJlbWFpbCI6ImdvbWV4Njc5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRDYkZoeVBjTmNjR2lnd0dyY01iR1gueC50SFQzZXJFRHF2TzE4WUVSOXM4aTRPdXNMRFptYSIsImV4cCI6MTY5NzcwODI3MH0.l3FzJNo19HlJ2naXDr9UdOl_N5aUkRsF3IOrRijdcZ4

{
    "nombre": "Bloque",
    "tipo": "Bloque",
    "x": 12,
    "y":10,
    "z": 20,
    "precio": 80,
    "description" : "Los bloques, en el contexto de la construcción, son unidades rectangulares o cuadradas de material de construcción utilizadas para crear muros, paredes, particiones y otros elementos estructurales o decorativos. Estos bloques pueden estar hechos de diferentes materiales, y cada tipo de bloque tiene sus propias características y aplicaciones específicas. A continuación, se describen algunos de los tipos más comunes de bloques utilizados en construcción"
}